server:
  port: 8081

spring:
  application:
    name: account-service
  main:
    banner-mode: off
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
